
package com.eurus.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "queryCaimanIslandsWs", targetNamespace = "http://ws.eurus.com", wsdlLocation = "http://192.168.128.132:9088/queryCaimanIslandsWs/queryCaimanIslandsWs.wsdl")
public class queryCaimanIslandsWs
    extends Service
{

    private final static URL QUERYCAIMANISLANDSWS_WSDL_LOCATION;
    private final static WebServiceException QUERYCAIMANISLANDSWS_EXCEPTION;
    private final static QName QUERYCAIMANISLANDSWS_QNAME = new QName("http://ws.eurus.com", "queryCaimanIslandsWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.128.132:9088/queryCaimanIslandsWs/queryCaimanIslandsWs.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYCAIMANISLANDSWS_WSDL_LOCATION = url;
        QUERYCAIMANISLANDSWS_EXCEPTION = e;
    }

    public queryCaimanIslandsWs() {
        super(__getWsdlLocation(), QUERYCAIMANISLANDSWS_QNAME);
    }

    public queryCaimanIslandsWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYCAIMANISLANDSWS_QNAME, features);
    }

    public queryCaimanIslandsWs(URL wsdlLocation) {
        super(wsdlLocation, QUERYCAIMANISLANDSWS_QNAME);
    }

    public queryCaimanIslandsWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYCAIMANISLANDSWS_QNAME, features);
    }

    public queryCaimanIslandsWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public queryCaimanIslandsWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QueryCaimanIslandsWsPortType
     */
    @WebEndpoint(name = "queryCaimanIslandsWsHttpSoap11Endpoint")
    public QueryCaimanIslandsWsPortType getQueryCaimanIslandsWsHttpSoap11Endpoint() {
        return super.getPort(new QName("http://ws.eurus.com", "queryCaimanIslandsWsHttpSoap11Endpoint"), QueryCaimanIslandsWsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryCaimanIslandsWsPortType
     */
    @WebEndpoint(name = "queryCaimanIslandsWsHttpSoap11Endpoint")
    public QueryCaimanIslandsWsPortType getQueryCaimanIslandsWsHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.eurus.com", "queryCaimanIslandsWsHttpSoap11Endpoint"), QueryCaimanIslandsWsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYCAIMANISLANDSWS_EXCEPTION!= null) {
            throw QUERYCAIMANISLANDSWS_EXCEPTION;
        }
        return QUERYCAIMANISLANDSWS_WSDL_LOCATION;
    }

}
