
package com.eurus.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "queryCaimanIslandsWsPortType", targetNamespace = "http://ws.eurus.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryCaimanIslandsWsPortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:queryAccountsByName")
    @WebResult(targetNamespace = "http://ws.eurus.com")
    @RequestWrapper(localName = "queryAccountsByName", targetNamespace = "http://ws.eurus.com", className = "com.eurus.ws.QueryAccountsByName")
    @ResponseWrapper(localName = "queryAccountsByNameResponse", targetNamespace = "http://ws.eurus.com", className = "com.eurus.ws.QueryAccountsByNameResponse")
    public String queryAccountsByName(
        @WebParam(name = "name", targetNamespace = "http://ws.eurus.com")
        String name);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sayHello")
    @WebResult(targetNamespace = "http://ws.eurus.com")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.eurus.com", className = "com.eurus.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.eurus.com", className = "com.eurus.ws.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "http://ws.eurus.com")
        String name);

    /**
     * 
     * @param name
     * @param branch
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:queryAccountsByNameAndBranch")
    @WebResult(targetNamespace = "http://ws.eurus.com")
    @RequestWrapper(localName = "queryAccountsByNameAndBranch", targetNamespace = "http://ws.eurus.com", className = "com.eurus.ws.QueryAccountsByNameAndBranch")
    @ResponseWrapper(localName = "queryAccountsByNameAndBranchResponse", targetNamespace = "http://ws.eurus.com", className = "com.eurus.ws.QueryAccountsByNameAndBranchResponse")
    public String queryAccountsByNameAndBranch(
        @WebParam(name = "name", targetNamespace = "http://ws.eurus.com")
        String name,
        @WebParam(name = "branch", targetNamespace = "http://ws.eurus.com")
        String branch);

}
